TREE=[
("admin","Administrativos","Organización, funciones de guardia, uniformidad y protección del interviniente","clipboard",[
 ("Funciones del personal de guardia","users",[("Funciones del personal de Guardia",18,"Obligaciones generales del personal"),("Directivo/a de Guardia",19),("Supervisor/a de Guardia",20),("Jefe/a de División de Guardia (CHARLY)",21),("Jefe/a de División de Guardia de Enfermería",22,"Jefe/a de División de Guardia de Enfermería (DELTA)"),("Encargado/a de la Central de Comunicaciones",22),("TATS Jefe/a de Equipo de Central de",23,"TATS Jefe/a de Equipo de Central de Comunicaciones"),("TATS Jefe/a de Equipo de Guardia de Protección",24,"TATS Jefe/a de Equipo de Guardia de PC Voluntaria (LIMA)"),("TATS Jefe/a de Equipo de Guardia de",26,"TATS Jefe/a de Equipo de Proc. Especiales (FENIX 0)"),("TATS de Guardia de Procedimientos Especiales",27,"TATS de Guardia de Proc. Especiales (FENIX 1)"),("Médico/a asistencial",28),("Enfermero/a asistencial",29),("TATS (Técnico/a Auxiliar de Transporte Sanitario)",30,"TATS asistencial"),("Psicólogo/a de Guardia (ROMEO)",31),("TATS Jefes/as de Equipo de División de Calidad",32),("TATS Adscritos a la Central de Comunicaciones",33),("Jefe/a de Equipo de la División de Guardia",33),("TATS de Mantenimiento de la Oﬁcina del Parque",34,"TATS de Mantenimiento del Parque (URO)")]),
 ("Uniformidad y EPIs","shield",[("UNIFORMIDAD y EPIs",35,"Uniformidad y EPIs")]),
 ("Intervinientes","hand",[("Accidente laboral con riesgo biológico",39),("Apoyo psicológico a intervinientes",41),("Autoprotección en casos sospechos de viruela del mono",42,"Autoprotección ante sospecha de viruela del mono"),("Contacto con meningitis bacteriana",43)]),
]),
("central","Central de Comunicaciones","Llamadas, prioridades, recursos, radio y consejos transtelefónicos","headset",[
 ("Llamadas y recursos","phone",[("Gestión de llamadas de emergencia",44),("Gestión de recursos",47),("Procedimiento radiotelefónico",53)]),
 ("Recomendaciones transtelefónicas","message",[("Foco de hemorragia activa",69),("Obstrucción de la vía aérea OVACE",69),("Pacientes politraumatizados por accidente de tráﬁco",72,"Politraumatizados por accidente de tráfico"),("Sospecha de Convulsiones",73),("Sospecha de Ictus",73),("Sospecha de parto en curso",75),("Sospecha de PCR y RCP transtelefónico",76),("Sospecha de Síndrome Coronario Agudo",78,"Sospecha de Síndrome Coronario Agudo (SCA)"),("Recomendaciones generales comunes a todas las llamadas",79,"Recomendaciones generales")]),
 ("Comunicación","chat",[("Técnicas de comunicación",80)]),
]),
("operativos","Operativos","Actuación general, coordinación con otros servicios, códigos y grandes incidentes","siren",[
 ("Actuación general","route",[("Actuación General",86),("Procedimiento en caso de accidente con unidades",94),("Actuación en casos de violencia de género",96)]),
 ("Coordinación con otros servicios","link",[("Con Bomberos",98),("PROCEDIMIENTO DE ACTUACIÓN CONJUNTA: SAMUR-",101,"Con Metro de Madrid"),("Con Policía Municipal",103),("PROCEDIMIENTO DE ACTUACIÓN CONJUNTA: SAMUR-",106,"Con Cuerpo Nacional de Policía"),("Con RENFE",109),("Con SAMUR Social",112),("Con SEAM",117),("Con UAPF",119),("Con Unidad de Medio Ambiente",120),("Policía Municipal. Dispositivo Electrónico de",121,"Policía Municipal. Dispositivo Electrónico de Control (DEC)")]),
 ("Violencia y atención sociosanitaria","heart-hand",[("Código VISEM",123),("Código VISNNA",126),("Atención sociosanitaria a mayores",130),("Atención Sociosanitaria a menores",133),("Circulación de Unidades en Convoy",137)]),
 ("Códigos de activación","code",[("Código 11",138,"Código 11 · PCR no traumática"),("Código 15.1",143),("Código 15",145),("Código 16",148),("Código 18",151,"Código 18 · Sepsis"),("Código 19",154,"Código 19 · TEP"),("Código 33",157),("Código 9",159,"Código 9 · Donación en asistolia"),("Código Crisis",161),("Código Infarto",163),("Códigos 13/13.1",166,"Códigos 13 / 13.1 · Ictus agudo")]),
 ("Escena, vehículos y documentación","truck",[("Conducción de vehículos sanitarios en emergencias",169),("Cumplimentación de los informes de asistencia",174),("Diagnóstico de Muerte",182,"Diagnóstico de muerte"),("Preaviso Hospitalario",198,"Preaviso hospitalario"),("Transferencia de pacientes",224)]),
 ("Grandes incidentes y riesgos","alert",[("Incidentes con múltiples víctimas y Triaje",192,"Incidentes con múltiples víctimas y Triaje (IMV)"),("Primera respuesta NRBQ",200),("Procedimiento de CECOR en un Dispositivo de Riesgo",207,"CECOR en Dispositivo de Riesgo Previsible (DRP)"),("Procedimiento de Incidentes Complejos. Código PIC",215,"Incidentes Complejos · Código PIC"),("Disturbios urbanos y Actos antisociales",183),("Farmacia Móvil",187,"Farmacia móvil (FOXTROT)"),("Huelga de hambre",188)]),
]),
("psico","Asistencia psicológica","Intervención del psicólogo de guardia en crisis, duelo, suicidio y violencia","brain",[
 ("Intervención psicológica","brain",[("Activación y actuación del psicólogo de guardia",237),("Asistencia psicológica en agresión sexual",239),("Asistencia psicológica en Código 9",239),("Asistencia psicológica en conducta suicida",240),("Asistencia psicológica en violencia de género",242),("Comunicación de malas noticias, inicio y proceso de duelo",244),("Crisis de ansiedad",245),("Intervención psicosocial en situaciones de crisis",246),("Situaciones de negociación",247)]),
]),
("sva","Soporte Vital Avanzado","Protocolos médicos SVA por especialidades","heart",[
 ("Generales, vía aérea y PCR","lungs",[("Analgesia y sedación",249),("Cuidados postparada",253),("Manejo avanzado de vía aérea",266),("Manejo de la vía aérea difícil",269),("Parada cardiorespiratoria",271),("PCR Traumática",276),("Reacción alérgica",279)]),
 ("Intoxicaciones","flask",[("Intoxicación por humo",255),("Intoxicaciones más frecuentes",258),("Manejo general del paciente intoxicado",264)]),
 ("Cardiovasculares","heart",[("Arritmias",281),("Crisis hipertensivas",285),("Edema agudo de pulmón",291),("Insuﬁciencia cardiaca aguda",293,"Insuficiencia cardiaca aguda / crónica agudizada"),("Isquemia arterial aguda",296),("Shock",297),("Síncope",299),("Síndrome Coronario Agudo con elevación del ST",302,"SCA con elevación del ST (SCACEST)"),("Síndrome Coronario Agudo sin elevación del ST",305,"SCA sin elevación del ST (SCASEST)")]),
 ("Digestivas","stomach",[("Abdomen agudo",308),("Hemorragia digestiva aguda",310)]),
 ("Endocrino-metabólicas","drop",[("Complicaciones de la diabetes",311),("Hiperglucemia por estrés",315),("Hipocalcemia - Hipercalcemia",316),("Hiponatremia",317),("Hipopotasemia - Hiperpotasemia",319)]),
 ("Nefrourológicas","kidney",[("Cólico renoureteral",321,"Cólico renoureteral (nefrítico)"),("Síndrome escrotal agudo",322)]),
 ("Neurológicas","neuro",[("Cefalea",325),("Coma",327),("Crisis / Estatus epiléptico",328),("Enfermedad vascular cerebral aguda",331),("Estado confusional agudo",333),("Síndrome discinético",334),("Síndrome vertiginoso",335)]),
 ("Obstétricas","baby",[("Asistencia al parto",336),("Urgencias obstétricas",338)]),
 ("Pediátricas","child",[("Asistencia al recién nacido",344),("Atención al menor bajo los efectos de alcohol",349,"Menor bajo efectos de alcohol o drogas"),("Crisis convulsivas",350),("Diﬁcultad respiratoria",352,"Dificultad respiratoria"),("Manejo del ictus en la edad pediátrica",356),("Quemaduras",359),("RCP pediátrica",361),("Urticaria, angioedema y anaﬁlaxia en pediatría",365,"Urticaria, angioedema y anafilaxia"),("Valoración del niño grave",367),("Valoración del paciente pediátrico politraumatizado",370)]),
 ("Agentes físicos","bolt",[("Lesiones por electricidad. Electrocución",378),("Paciente con hipotermia",379),("Paciente quemado",382),("Patologías por inmersión. Ahogamiento",384),("Urgencias por calor",385)]),
 ("Psiquiátricas","mind",[("Urgencias psiquiátricas",387)]),
 ("Respiratorias","lungs",[("Crisis asmática aguda",391),("Exacerbaciones agudas del paciente con EPOC",393),("Tromboembolismo pulmonar",395)]),
 ("Traumatológicas","bone",[("Shock hemorrágico de origen traumático",397),("Síndrome de aplastamiento",400),("Traumatismo craneoencefálico",401),("Traumatismo de abdomen",406),("Traumatismo de tórax",408),("Traumatismo pélvico",415),("Traumatismos ortopédicos",417),("Traumatismos vertebro-medulares",419),("Valoración inicial del paciente politraumatizado",421)]),
]),
("svb","Soporte Vital Básico","Actuación de las unidades de SVB: valoración, patologías y trauma","cross",[
 ("Patologías y situaciones","pulse",[("Atención y traslado al paciente psiquiátrico",427),("Convulsiones",432),("Desﬁbrilación externa automática",434,"Desfibrilación externa automática (DEA)"),("Instrumental adultos",436),("Instrumental pediátrico",439),("Obstrucción de la vía aérea por cuerpo extraño",441,"Obstrucción de la vía aérea (OVACE)"),("Patologías de origen cardiovascular",444),("Posible enfermedad vascular cerebral aguda",447,"Posible ictus"),("Posible intoxicación por drogas de abuso",450),("Posible patología de origen respiratorio",453),("Posible shock hipovolémico de origen traumático",455),("Solicitud de USVA",456)]),
 ("Traumatismos","bone",[("Abdominal",460,"Trauma abdominal"),("Columna vertebral",462),("Craneoencefálico",464,"Trauma craneoencefálico"),("Torácico",466,"Trauma torácico"),("Valoración inicial del paciente politraumatizado",469)]),
 ("Valoración","eye",[("Valoración del niño grave",475),("Valoración del paciente adulto",478)]),
]),
("tecnicas","Técnicas","Paso a paso de las técnicas sanitarias: cardiacas, vasculares, vía aérea, trauma…","tools",[
 ("Cardiacas","heart",[("Cardioversión",483),("Desﬁbrilación de doble secuencia",484,"Desfibrilación de doble secuencia (DDS)"),("Desﬁbrilación",485,"Desfibrilación"),("Dispositivo de compresiones torácicas automático",486),("Electrodiagrama de 12 derivaciones",488,"ECG de 12 derivaciones"),("Hipotermia terapéutica en la Parada cardiaca",491),("Marcapasos temporal no invasivo",493),("Masaje del seno carotídeo",495),("Pericardiocentesis",496),("Toracotomía de reanimación",497)]),
 ("Ecografía","wave",[("Exploración Ecográﬁca Extrahospitalaria",499,"Exploración ecográfica extrahospitalaria")]),
 ("Obstetricia","baby",[("Cesárea postparada",504),("Episotomía Mediolateral",505,"Episiotomía mediolateral")]),
 ("Signos vitales","pulse",[("Signos Vitales",511,"Signos vitales")]),
 ("Higiene y seguridad","soap",[("Técnicas y medidas higiénicas",514),("Test rápido de antígeno de SARS-CoV-2",517)]),
 ("Básicas y sondajes","tube",[("Extracción de lentes de contacto",506),("Lavado Ocular",507,"Lavado ocular"),("Administración de comprimido bucodispersable",508),("Medición de Temperatura central mediante sonda",508,"Temperatura central con sonda esofágica"),("Relación con el paciente",509),("Situaciones especiales",510),("Administración de carbón activado",519),("Lavado gástrico",520),("Sondaje gástrico",521),("Sondaje vesical",522)]),
 ("Trauma","bandage",[("Control de hemorragias",523),("Inmovilización niño. SIPE",531,"Inmovilización del niño (SIPE®)"),("Parche oclusivo torácico",535),("Técnica de escarotomía",536),("Técnicas de inmovilización",537),("Técnicas de movilización de pacientes",540),("Tratamiento inicial de heridas",545),("Tratamiento inicial de las quemaduras",546),("Vendajes",547)]),
 ("Vasculares","syringe",[("Accesos vasculares en niños",549),("Accesos vasculares especiales",550),("Administración de fármacos por vía intravenosa",556),("Analítica de sangre",557),("Canalización de vías venosas centrales",558),("Canalización de vías venosas periféricas ecoguiadas",559),("Canalización de vías venosas periféricas",561),("Cateterización de la vena umbilical",562),("Determinación de INR",563),("Técnica de medición de glucemia",565),("Obtención de sangre arterial",568),("Manipulación de material de acceso vascular",568),("Priorización de la localización de accesos",570,"Priorización de accesos vasculares"),("Test de Troponina de alta sensibilidad",570),("Vía Intraósea, sistema EZ-IO",571,"Vía intraósea (EZ-IO)")]),
 ("Vía aérea y respiración","lungs",[("Administración de fármacos con cámara de inhalación",576),("Administración de fármacos por vía inhalatoria",577),("Administración endotraqueal de medicamentos",578),("AIRTRAQ",579,"Airtraq®"),("ASPIRACIÓN DE SECRECIONES",580,"Aspiración de secreciones por tubo endotraqueal"),("Cricotiroidotomía",580),("Introductor de Frova",581),("Intubación endotraqueal",582),("Medición de COHb",585),("Medición de ETCO2",586),("Medición de SatO2",587),("Permeabilización básica de la vía aérea",588),("Toracocentesis",590),("Toracostomía",591),("Ventilación Mecánica No Invasiva",592,"Ventilación mecánica no invasiva (VMNI)")]),
]),
]

STOPS=[("Tipos de asistencia psicológica",225),("Procedimiento psicológico",236),("Atención a víctimas de violencia sexual",130)]
